name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: |
          cd client && npm install && cd .. && npm install
      - name: lint
        run: |
          cd client && npm run lint && cd .. && npm run lint
      - name: build
        run: |
          cd client && npm run build && cd .. && npm run build
      - name: Start server in background
        run: npm run start:test &
      - name: component tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          working-directory: ./client
          wait-on: http://localhost:8080
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: e2e tests
        uses: cypress-io/github-action@v3
        with:
          install: false
          project: ./client
          start: npm run start:test
          wait-on: http://localhost:8080

  deploy:
    needs: [build]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only

  tag_release:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # eca2b69f9e2c24be7decccd0f15fdb1ea5906598 before
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main